# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capistrano-appiphany"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ivan Vega"]
  s.date = "2011-10-17"
  s.description = "Appiphany recipes for Capistrano"
  s.email = "ivan@appiphany.com.au"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "Rakefile",
    "VERSION",
    "capistrano-appiphany.gemspec",
    "lib/appiphany/capistrano/apache.rb",
    "lib/appiphany/capistrano/base.rb",
    "lib/appiphany/capistrano/common.rb",
    "lib/appiphany/capistrano/passenger.rb",
    "lib/appiphany/capistrano/thinking_sphinx.rb"
  ]
  s.homepage = "http://github.com/ivanyv/capistrano-appiphany"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Appiphany recipes for Capistrano"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

